
package com.tanjer.heart_beat.servicegenerate;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-14T16:34:25.641+05:30
 * Generated source version: 3.5.9
 *
 */
public final class PharmacySaleService_PharmacySaleService_Client {

    private static final QName SERVICE_NAME = new QName("http://dtts.sfda.gov.sa/PharmacySaleService", "PharmacySaleService");

    private PharmacySaleService_PharmacySaleService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PharmacySaleService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PharmacySaleService_Service ss = new PharmacySaleService_Service(wsdlURL, SERVICE_NAME);
        PharmacySaleService port = ss.getPharmacySaleService();

        {
        System.out.println("Invoking notifyPharmacySale...");
        com.tanjer.heart_beat.servicegenerate.PharmacySaleServiceRequest _notifyPharmacySale_pharmacySaleServiceRequest = null;
        try {
            com.tanjer.heart_beat.servicegenerate.PharmacySaleServiceResponse _notifyPharmacySale__return = port.notifyPharmacySale(_notifyPharmacySale_pharmacySaleServiceRequest);
            System.out.println("notifyPharmacySale.result=" + _notifyPharmacySale__return);

        } catch (ServiceError e) {
            System.out.println("Expected exception: ServiceError has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
