
package com.tanjer.heart_beat.servicegenerate;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-11-14T16:34:25.822+05:30
 * Generated source version: 3.5.9
 */

@WebFault(name = "ServiceError", targetNamespace = "http://dtts.sfda.gov.sa/PharmacySaleService")
public class ServiceError extends Exception {

    private com.tanjer.heart_beat.servicegenerate.FaultBean faultInfo;

    public ServiceError() {
        super();
    }

    public ServiceError(String message) {
        super(message);
    }

    public ServiceError(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ServiceError(String message, com.tanjer.heart_beat.servicegenerate.FaultBean serviceError) {
        super(message);
        this.faultInfo = serviceError;
    }

    public ServiceError(String message, com.tanjer.heart_beat.servicegenerate.FaultBean serviceError, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = serviceError;
    }

    public com.tanjer.heart_beat.servicegenerate.FaultBean getFaultInfo() {
        return this.faultInfo;
    }
}
